name: cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dart_console: ^1.1.2
  http: ^0.13.5
  dart_clipboard: ^0.3.0
#  chat_gpt_sdk: ^1.0.2+1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
