name: back
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  js: ^0.6.5
  http: ^0.13.5
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
  webdev: ^2.7.12
